ports:
  - port: 3333
    onOpen: open-browser
    visibility: public
tasks:
  - init: yarn
    command: >
      cp .env.example .env;
      docker-compose up -d;
      yarn typeorm migration:run;
      yarn dev
